//! `ExpandS` for ML-DSA secret vectors.
//!
//! FIPS 204 uses `ExpandS(ρ')` during `ML-DSA.KeyGen_internal` to derive the
//! small secret vectors `s1` and `s2` from the private 64-byte seed `ρ'`. Unlike
//! `ExpandA(ρ)`, whose public output is already in the NTT domain, `ExpandS(ρ')`
//! returns ordinary polynomial vectors with small centered coefficients.
//!
//! The output dimensions are parameter-set dependent: `s1` contains `l`
//! polynomials, `s2` contains `k` polynomials, and every polynomial has
//! `N = 256` coefficients in `[-η, η]`.
//!
//! ```text
//! ML-DSA-44: s1 has 4 polynomials, s2 has 4 polynomials
//! ML-DSA-65: s1 has 5 polynomials, s2 has 6 polynomials
//! ML-DSA-87: s1 has 7 polynomials, s2 has 8 polynomials
//! ```
//!
//! Each polynomial is sampled independently by deriving a 66-byte
//! `RejBoundedPoly` seed from `ρ'` plus a two-byte index. The `s1` indices start
//! at `0`; the `s2` indices continue after `s1`, which keeps the polynomial
//! domains separate while using the same `ρ'`.

use crate::error::DilithiumResult;
use crate::params::ParameterSet;
use crate::poly::PolyVector;
use crate::sampling::coefficients::{SamplingIndex, derive_indexed_bounded_seed};
use crate::sampling::constants::ExpandSSeed;
use crate::sampling::limits::SamplingLimits;
use crate::sampling::rejection::rej_bounded_poly_with_limits;
use crate::sampling::report::{Sampled, SamplingReport};

/// FIPS 204 Algorithm 33, `ExpandS(ρ')`.
///
/// This convenience wrapper runs without optional Table 3 caps and returns only
/// the sampled secret vectors `(s1, s2)`. Use
/// [`expand_s_with_limits`] when callers need instrumentation or explicit
/// Table 3 loop/XOF caps.
pub fn expand_s(
    seed: ExpandSSeed,
    parameter_set: ParameterSet,
) -> DilithiumResult<(PolyVector, PolyVector)> {
    let sampled = expand_s_with_limits(seed, parameter_set, SamplingLimits::default())?;
    Ok(sampled.into_value())
}

/// `ExpandS` with optional limits and aggregated instrumentation.
///
/// `ExpandS(ρ')` samples `s1` with dimension `l` and `s2` with dimension `k`.
/// Each polynomial is generated by `RejBoundedPoly`, which uses `H = SHAKE256`
/// and `CoeffFromHalfByte` to produce coefficients in `[-η, η]`.
///
/// FIPS derives each bounded-polynomial seed as:
///
/// ```text
/// ρ' || IntegerToBytes(index, 2)
/// ```
///
/// This implementation follows that indexing directly:
///
/// ```text
/// for r in 0..l:
///     s1[r] = RejBoundedPoly(ρ' || IntegerToBytes(r, 2))
///
/// for r in 0..k:
///     s2[r] = RejBoundedPoly(ρ' || IntegerToBytes(r + l, 2))
/// ```
///
/// The returned [`Sampled`] value contains the `(s1, s2)` pair plus one
/// aggregated [`SamplingReport`]. That report absorbs every individual
/// `RejBoundedPoly` report, so callers can inspect the total loop count and XOF
/// bytes consumed across the whole `ExpandS(ρ')` derivation.
pub fn expand_s_with_limits(
    seed: ExpandSSeed,
    parameter_set: ParameterSet,
    limits: SamplingLimits,
) -> DilithiumResult<Sampled<(PolyVector, PolyVector)>> {
    limits.validate()?;

    let mut s1 = Vec::with_capacity(parameter_set.core.l);
    let mut s2 = Vec::with_capacity(parameter_set.core.k);
    let mut report = SamplingReport::default();

    for row in 0..parameter_set.core.l {
        let derived_seed =
            derive_indexed_bounded_seed(seed.bytes(), SamplingIndex::from_usize(row));
        let sampled = rej_bounded_poly_with_limits(derived_seed, parameter_set.core.eta, limits)?;
        let (value, sampled_report) = sampled.into_parts();
        report.absorb(sampled_report);
        s1.push(value);
    }

    for row in 0..parameter_set.core.k {
        let derived_seed = derive_indexed_bounded_seed(
            seed.bytes(),
            SamplingIndex::from_usize(row + parameter_set.core.l),
        );
        let sampled = rej_bounded_poly_with_limits(derived_seed, parameter_set.core.eta, limits)?;
        let (value, sampled_report) = sampled.into_parts();
        report.absorb(sampled_report);
        s2.push(value);
    }

    Ok(Sampled::new(
        (
            PolyVector::from_polys(parameter_set.core.l, s1)?,
            PolyVector::from_polys(parameter_set.core.k, s2)?,
        ),
        report,
    ))
}
