//! Operating-system randomness used by the external ML-DSA APIs.
//!
//! FIPS 204's public `ML-DSA.KeyGen()` and hedged `ML-DSA.Sign()` paths need
//! fresh bytes from an approved random bit generator. This POC obtains those
//! bytes from the platform source exposed by `getrandom` and keeps deterministic
//! seed/rnd entry points separate for KATs and conformance tests.

use crate::error::{DilithiumError, DilithiumResult};

/// Returns `NBYTES` freshly generated bytes from the operating system.
pub(crate) fn random_bytes<const NBYTES: usize>() -> DilithiumResult<[u8; NBYTES]> {
    let mut bytes = [0u8; NBYTES];
    getrandom::fill(&mut bytes)
        .map_err(|_| DilithiumError::Unsupported("random bit generation failed"))?;
    Ok(bytes)
}
